// ========== CONFIGURACIÓN (modifica aquí textos y respuestas) ==========
export const CONFIG = {
  nombre: 'Vendy',
  apodo: 'MI preciosa',
  ciudades: ['Cuenca', 'Quito'],
  chisteNomos: 'la casa de los nomos del amor',
  artistas: ['Guardaraya', 'Machaka', 'C. Tangana','Panda', 'Empire of the Sun'],
  respuestas: {
    pista1: ['cuenca', 'quito'],
    pista2: 'panda',
    pista3: 'amor',
    pista4: 'iglu',      // casa de Chilly Willy
    pista5: 'francia',   // La república de...
    pista6: 'opiniones', // Datos no...
    pista7: ['piensa', 'piensaf', 'piensaffff' ]   // "Será que es amor" (Ilyari): "El amor se hace. No se piensa"
  },
  mensajeFinal: 'Llegaste al final del código secreto… y al mío también. ¿Qué dices?',
  mensajeSi: 'Sabía que sí 😏💘',
  // Video de YouTube que se reproduce al aceptar (ID: Será que es amor - Radio Reflejo)
  youtubeVideoId: 'PQR4-DXLYOs',
  youtubeStartSeconds: 17, // El video empieza en el segundo 17
  // Letra completa (from = segundos desde el inicio del VIDEO; el video arranca en 17)
  letraSeráQueEsAmor: [
    { from: 17, text: 'Radio Reflejo' },
    { from: 19, text: 'La voz de los enamorados' },
    { from: 22, text: '69.9 desde la mitad del mundo' },
    { from: 25, text: 'Música para escuchar' },
    { from: 28, text: 'Con el corazón encendido' },
    { from: 31, text: 'Y la luz apagada' },
    { from: 34, text: 'Una ilusión se despierta' },
    { from: 37, text: 'Y en ti se proyecta' },
    { from: 40, text: 'La imagen perfecta' },
    { from: 43, text: '¿Será que es amor?' },
    { from: 46, text: 'Abierto mi shungo se abierto' },
    { from: 49, text: 'Después de estar muerto' },
    { from: 52, text: 'Ahuevado' },
    { from: 54, text: 'Sediento' },
    { from: 56, text: '¿Será que es amor?' },
    { from: 59, text: 'Gracias diosito lindo' },
    { from: 62, text: 'Por poder sentir esto de nuevo' },
    { from: 66, text: 'Hoy te quiero escuchar' },
    { from: 69, text: 'Tu rostro tocar' },
    { from: 72, text: 'Contigo sudar' },
    { from: 75, text: 'Hoy te quiero escuchar' },
    { from: 78, text: 'Tu rostro tocar' },
    { from: 81, text: 'Contigo sudar' },
    { from: 84, text: 'Es lo que siento' },
    { from: 87, text: 'And ohhh my love' },
    { from: 90, text: 'My darling' },
    { from: 93, text: 'Are you' },
    { from: 96, text: 'El amor se hace' },
    { from: 99, text: 'No se piensa ps' },
    { from: 102, text: 'Y cuando estemos frente a frente' },
    { from: 106, text: 'Sin filtro sin lente' },
    { from: 109, text: 'Desnudos realmente' },
    { from: 112, text: '¿Será que es amor?' },
    { from: 115, text: 'Ay dios no' },
    { from: 118, text: '¿Y será que me quiere así' },
    { from: 121, text: 'Con todos mis tereques?' },
    { from: 124, text: 'Y si este castillo se estrella' },
    { from: 127, text: 'La nueve degüella' },
    { from: 130, text: 'Rayando la mente' },
    { from: 133, text: 'Mente' },
    { from: 135, text: 'Mente' },
    { from: 137, text: 'Mente' },
    { from: 139, text: '¿Será que es amor?' },
    { from: 142, text: 'Pero ¿quién sabe, quizás, tal vez?' },
    { from: 146, text: 'Ah que chukchas' },
    { from: 149, text: 'Hoy te quiero escuchar' },
    { from: 152, text: 'Tu rostro tocar' },
    { from: 155, text: 'Contigo sudar' },
    { from: 158, text: 'Hoy te quiero escuchar' },
    { from: 161, text: 'Tu rostro tocar' },
    { from: 164, text: 'Contigo sudar' },
    { from: 167, text: 'Es lo que siento' },
    { from: 170, text: '0962750...' },
    { from: 173, text: 'Es lo que siento' },
    { from: 176, text: '¿aló?' },
    { from: 178, text: 'Eso que siento' },
    { from: 181, text: 'Que sea lo que sea' },
    { from: 184, text: 'Eso que siento' },
    { from: 187, text: '¿Será que es amor?' },
  ],
  // Frases que se muestran al acertar cada pista (una por pregunta, en orden)
  felicitaciones: [
    '¡Exacto, mi amor! Es nuestra ciudad de los nomos 💕',
    '¡Así es! Cuánto me conoces, preciosa 💘',
    '¡Sí! Tú y yo = eso siempre ✨',
    '¡Correcto! Chilly Willy estaría orgulloso 🧊',
    '¡Lo tienes! La república de nuestro corazón 🇫🇷',
    '¡Perfecto! Datos no opiniones — y tú eres mi dato favorito 😏💕',
    '¡Eso es! El amor se hace, no se piensa — como lo nuestro 💘',
  ],
}
